name: "🛣️ Roadmap Template"
description: Roadmap Issue template
title: "Roadmap-0.X.Y"
labels: ["🏗️ ADR", "🛣️ Roadmap"]
assignees:
  - shinGangan
body:
  - type: markdown
    attributes:
      value: Roadmap Issue template
  - type: textarea
    id: author
    attributes:
      label: "abstract"
      value: |
        # Roadmap-0.X.Y

        - Author: @xyz
        - Reviewers:
          - none
    validations:
      required: true
  # Status
  - type: input
    id: status
    attributes:
      label: Status
      value: Draft
      placeholder: Draft
    validations:
      required: false
  # Context
  - type: textarea
    id: context
    attributes:
      label: Context
      value: |
        XXX v0.X.Y において実施することを整理する。次バージョン移行のためにADRを残す。
        ただし、各機能・検討事項の詳細は別途ADRを立てる。
    validations:
      required: true
  # Decisions
  - type: textarea
    id: decisions
    attributes:
      label: Decisions
      value: |
        #### Draft: ADR

        - [ ]

        #### Issues

        https://github.com/shinGangan/{foo}/milestone/{number}

    validations:
      required: false
  # Consequences
  - type: textarea
    id: consequences
    attributes:
      label: Consequences
      value: |
        Comment Draft

        #### Release Note

        - TODO: Release Noteのリンク
    validations:
      required: false
